// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd6qqznpH32iyZ1Xh1Gcu7mTS70lyhIWo',
    appId: '1:620395946470:web:f9ff1e0733e03fb49e3627',
    messagingSenderId: '620395946470',
    projectId: 'my-hello-project-1a80e',
    authDomain: 'my-hello-project-1a80e.firebaseapp.com',
    storageBucket: 'my-hello-project-1a80e.appspot.com',
    measurementId: 'G-JR4L2ZTVFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFEXqF-JYJ8gO7Y0Dcw9YgVT3FaMzKglE',
    appId: '1:620395946470:android:ef95f9bd4f0165089e3627',
    messagingSenderId: '620395946470',
    projectId: 'my-hello-project-1a80e',
    storageBucket: 'my-hello-project-1a80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZRxHyRevOAGHpayi-cyhqVg6AnN9ZGI',
    appId: '1:620395946470:ios:c0ab14e574a076b29e3627',
    messagingSenderId: '620395946470',
    projectId: 'my-hello-project-1a80e',
    storageBucket: 'my-hello-project-1a80e.appspot.com',
    iosClientId: '620395946470-dsafk11pcg8ckrr4ati8skr8np00jpf8.apps.googleusercontent.com',
    iosBundleId: 'com.welcometomyapp.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGZRxHyRevOAGHpayi-cyhqVg6AnN9ZGI',
    appId: '1:620395946470:ios:c0ab14e574a076b29e3627',
    messagingSenderId: '620395946470',
    projectId: 'my-hello-project-1a80e',
    storageBucket: 'my-hello-project-1a80e.appspot.com',
    iosClientId: '620395946470-dsafk11pcg8ckrr4ati8skr8np00jpf8.apps.googleusercontent.com',
    iosBundleId: 'com.welcometomyapp.notes',
  );
}
